#!/bin/bash

#SBATCH --partition=smp
#SBATCH --account=m2_jgu-salmosex
#SBATCH --time=0-20:00:00
#SBATCH --ntasks=1
#SBATCH --job-name=gzipfiles
#SBATCH -o mein_job.log
#SBATCH -e mein_job.err

cd /lustre/miifs01/project/m2_jgu-salmosex/nina/data/383917

# Files to gzip
files=(
    "SRR5468475_1.fastq"
    "SRR5468489_2.fastq"
    "SRR5468491_2.fastq"
)

for file in "${files[@]}"; do
    if [[ -f "$file" ]]; then
        echo "Gzipping file: $file"
        gzip "$file" && echo "Successfully gzipped $file" >> mein_job.log || echo "Error: Failed to gzip $file" >> mein_job.err
    else
        echo "Error: File $file not found" >> mein_job.err
    fi
done
